# Generated by packaging/render-packages.sh — do not edit by hand.
# Tap: brew tap levantar-ai/loadr https://github.com/levantar-ai/loadr
class Loadr < Formula
  desc "Modern load-testing tool: declarative YAML, embedded JS, many protocols"
  homepage "https://loadr.io"
  version "1.24.1"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.1/loadr-aarch64-apple-darwin.tar.gz"
      sha256 "a7b4ce34c52b590992af6edc8823541b0b8a6e06b94f217fae0d9a07b95bc69a"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.1/loadr-x86_64-apple-darwin.tar.gz"
      sha256 "f087a0130a71b66b439561c20fb91a910d16fe7b0ac361f4b142010e28e535a6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.1/loadr-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "dc67fee9037377aec6e716290949bfc152c2bab5acf8e3f77536e661045baa8a"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.1/loadr-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "efe5239bd755742c0eaaa2a6641f741d74f7371b8bf247b31584cea6a179ed1f"
    end
  end

  def install
    bin.install "loadr"
  end

  test do
    assert_match "loadr", shell_output("#{bin}/loadr --version")
  end
end
