# Generated by packaging/render-packages.sh — do not edit by hand.
# Tap: brew tap levantar-ai/loadr https://github.com/levantar-ai/loadr
class Loadr < Formula
  desc "Modern load-testing tool: declarative YAML, embedded JS, many protocols"
  homepage "https://loadr.io"
  version "1.24.0"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.0/loadr-aarch64-apple-darwin.tar.gz"
      sha256 "bd06f8e2898d6e55e826b60f2a0d5a0a52da98722216a0d3e74d7e6499340166"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.0/loadr-x86_64-apple-darwin.tar.gz"
      sha256 "5ea1b2e590b5702db239930e6d81e870a9bf12163ae63c90f95ca96e9da922a8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.0/loadr-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "34bed9aa22ac1c19c6b751cc14896e5afeeb05e24659c6e02bf36f6412862cf8"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.24.0/loadr-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d9bdccb1a4f3ee18871a15c7ee719436966c64d9132b4d047244704cc026a817"
    end
  end

  def install
    bin.install "loadr"
  end

  test do
    assert_match "loadr", shell_output("#{bin}/loadr --version")
  end
end
