//! `loadr scenario "<description>"` — generate a validated scenario from natural
//! language via an LLM (Anthropic; set `ANTHROPIC_API_KEY`).

use std::path::PathBuf;

use clap::Args;
use owo_colors::OwoColorize;

use loadr_ai::{generate_plan, Anthropic};

#[derive(Args)]
pub struct ScenarioArgs {
    /// Natural-language description, e.g. "500 rps on /checkout for 10m"
    pub prompt: String,
    /// Output YAML path (default: stdout)
    #[arg(short, long)]
    pub output: Option<PathBuf>,
    /// Model id (default: a current Claude)
    #[arg(long)]
    pub model: Option<String>,
    /// Don't embed the loadr JSON Schema in the prompt (smaller, less strict)
    #[arg(long)]
    pub no_schema: bool,
}

pub fn execute(args: ScenarioArgs) -> anyhow::Result<i32> {
    let provider = Anthropic::from_env(args.model.clone())?;
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?;
    let yaml = runtime.block_on(generate_plan(&provider, &args.prompt, !args.no_schema))?;

    let header = format!("# Generated by `loadr scenario` from: {}\n", args.prompt);
    match &args.output {
        Some(p) => {
            std::fs::write(p, format!("{header}{yaml}"))?;
            eprintln!("{} wrote {}", "scenario:".green().bold(), p.display());
        }
        None => print!("{header}{yaml}"),
    }
    Ok(0)
}
